### ISSUE TITLE
Wrong request but 200 OK 

### ISSUE THREAD

**Issue by sklerakuku** [Cool-Andrey/Calculating#1]
```json
{
    "expression": "7a-9k"
}
```

Response:  （CODE 200 OK) 
```json
{
    "result": "-9.00"
}
```

🐱 O(∩_∩)O 哈哈

**Comment by golang-one-love** [comment]
Блин... Чо поставил?

**Comment by golang-one-love** [comment]
я слепой...

**Comment by golang-one-love** [comment]
> ```json
> {
>     "expression": "7a-9k"
> }
> ```
> 
> Response: （CODE 200 OK)
> 
> ```json
> {
>     "result": "-9.00"
> }
> ```
> 
> 🐱 O(∩_∩)O 哈哈

ответь пж... Я уже пердечный сриступ словил

**Comment by golang-one-love** [comment]
Я сделал проверку. Если хочешь/можешь, то перепроверь пожалуйста.
